# Control Flow
## Practice Problems

### 1. Write a conditional that prints different messages if a bank account balance is below `$`3,000, between `$`3,000 and `$`10,000, or over `$`10,000.

HINT: You can check if a value `x` is between two other values with a condition like `5 <= x <= 10`, but you can also solve this problem by strategically ordering conditions.

In [5]:
# Your code goes here
import random
x = random.randint(0, 20001)

In [6]:
if x < 3000:
    print("This value is lower than $3,000")
elif 3000 <= x <= 10000:
    print("This value is including and between $3,000 and $10,000")
elif x > 10000:
    print("This value is greater than $10,000")

This value is lower than $3,000

<details>
  <summary>Answer</summary>

  ```python
  balance = 3000

  if balance < 3000:
    print('Your balance is under $3,000')
  elif balance <= 10000:
    print('Your balance is between $3,000 and $10,000')
  else:
    print('Your balance is over $10,000.')

  # This would also be a valid solution:
  
  if balance < 3000:
    print('Your balance is under $3,000')
  elif balance >= 3000 and balance <= 10000:
    print('Your balance is between $3,000 and $10,000')
  else:
    print('Your balance is over $10,000.')

  # And so would this:

  if balance < 3000:
    print('Your balance is under $3,000')
  elif 3000 <= balance <= 10000:
    print('Your balance is between $3,000 and $10,000')
  else:
    print('Your balance is over $10,000.')
  ```
</details>

In [7]:
if x < 3000:
    print(f"This value is lower than $3,000. It is {x}")
elif 3000 <= x <= 10000:
    print(f"This value is including and between $3,000 and $10,000. It is {x}")
elif x > 10000:
    print(f"This value is greater than $10,000. It is {x}")

This value is lower than $3,000. It is 1168

### 2. Create a list, `books`, containing the following items: `'War and Peace', 'Pride and Prejudice', 'Mockingjay', 'Three Musketeers', 'The Adventures of Robinson Crusoe', 'Yevgeniy Onegin'`. Then:

- Using slicing or indexing, create the following:
    - An empty list
    - The last item of `books`
    - List of three items: 'Three Musketeers', 'The Adventures of Robinson Crusoe', 'Yevgeniy Onegin'.
   
- Using list methods:
    - Remove 'Pride and Prejudice' from the list.
    - Insert 'Harry Potter and the Chamber of Secrets' after 'Mockingjay'.

HINT: Try using the same number as the starting index and ending index of a slice. Useful list methods include `remove()` and `insert()`.

In [30]:
# Your code goes here
books = ['War and Peace', 'Pride and Prejudice', 'Mockingjay', 'Three Musketeers', 'The Adventures of Robinson Crusoe', 'Yevgeniy Onegin']
type(books)

list

In [31]:
# empty list
print(books[0:0])

# last item of books
last_item = books[-1]
print(last_item)

#list of three items 'Three Musketeers', 'The Adventures of Robinson Crusoe', 'Yevgeniy Onegin'
# two ways to do this, since they are ordered as the last 3 consecutive items, I can use a negative index value
last_three = books[-3:]
print(last_three)

# or, I can run an in loop
three = ['Three Musketeers', 'The Adventures of Robinson Crusoe', 'Yevgeniy Onegin']
grouped = []
for i in books:
    if i in three:
        grouped.append(i)
        print(grouped)

# or list comprehension too
three2 = [i for i in books if i in three]
print(three2)

[]
Yevgeniy Onegin
['Three Musketeers', 'The Adventures of Robinson Crusoe', 'Yevgeniy Onegin']
['Three Musketeers']
['Three Musketeers', 'The Adventures of Robinson Crusoe']
['Three Musketeers', 'The Adventures of Robinson Crusoe', 'Yevgeniy Onegin']
['Three Musketeers', 'The Adventures of Robinson Crusoe', 'Yevgeniy Onegin']

In [32]:
# remove Pride and Prejudice
books.remove("Pride and Prejudice")
print(books)

# Insert 'Harry Potter and the Chamber of Secrets' after 'Mockingjay'
books.insert(2, 'Harry Potter and the Chamber of Secrets')
print(books)

['War and Peace', 'Mockingjay', 'Three Musketeers', 'The Adventures of Robinson Crusoe', 'Yevgeniy Onegin']
['War and Peace', 'Mockingjay', 'Harry Potter and the Chamber of Secrets', 'Three Musketeers', 'The Adventures of Robinson Crusoe', 'Yevgeniy Onegin']

<details>
  <summary>Answer</summary>

  ```python
  books = ['War and Peace', 'Pride and Prejudice', 'Mockingjay', 'Three Musketeers', 'The Adventures of Robinson Crusoe', 'Yevgeniy Onegin']

  # an empty list
  books[0:0]

  # the last item
  books[-1]

  # the last three items
  books[-3:]

  # remove 'Pride and Prejudice'
  books.remove('Pride and Prejudice')

  # Insert Harry Potter and the Chamber of Secrets after Mockingjay
  # If you did not remove Pride and Prejudice, the index would be 3, not 2
  books.insert(2, 'Harry Potter and the Chamber of Secrets')

  books
  ```
</details>

### 3. Given the list `people`, sort it by people's first name, last name and age. Store the sorted lists as `by_first_name`, `by_last_name`, and `by_age`, respectively.  
`people = [('Mark', 'Harrison', 56), ('Ken', 'Wolseley', 23), ('Emily', 'Robinson', 77)]`

HINT 1: We want our sorting function to return a new list, rather than modifying in place.

HINT 2: `sorted()` accepts a `key` argument. This argument is the name of a function to use when sorting list elements.

In [40]:
# Your code goes here
people = [('Mark', 'Harrison', 56), ('Ken', 'Wolseley', 23), ('Emily', 'Robinson', 77)]
print(people[1][2])
print(type(people[1]))

23
<class 'tuple'>

In [ ]:
# sort by multiple elements, first_name, then last_name, then age
people.sort(key=lambda x: (x[0], x[1], x[2]))
people

In [44]:
# sort by first name, as it is the first element
people.sort(key=lambda x: x[0])
print(people)

# sort by last name
people.sort(key=lambda x: x[1])
print(people)

# sort by age
people.sort(key=lambda x: x[2])
print(people)

[('Emily', 'Robinson', 77), ('Ken', 'Wolseley', 23), ('Mark', 'Harrison', 56)]
[('Mark', 'Harrison', 56), ('Emily', 'Robinson', 77), ('Ken', 'Wolseley', 23)]
[('Ken', 'Wolseley', 23), ('Mark', 'Harrison', 56), ('Emily', 'Robinson', 77)]

In [45]:
# or these methods from the answer
def get_first_item(lst):
    return lst[0]
def get_second_item(lst):
    return lst[1]
def get_third_item(lst):
    return lst[2]

sort_first_name = sorted(people, key=get_first_item)
sort_last_name = sorted(people, key=get_second_item)
sort_age = sorted(people, key=get_third_item)

print(sort_first_name)
print(sort_last_name)
print(sort_age)

[('Emily', 'Robinson', 77), ('Ken', 'Wolseley', 23), ('Mark', 'Harrison', 56)]
[('Mark', 'Harrison', 56), ('Emily', 'Robinson', 77), ('Ken', 'Wolseley', 23)]
[('Ken', 'Wolseley', 23), ('Mark', 'Harrison', 56), ('Emily', 'Robinson', 77)]

<details>
  <summary>Answer</summary>

  ```python
  #Here, we have to write functions to get the first, second, and third items in a list.
  #Then, we can use those functions as the keys for sorted().

  people = [('Mark', 'Harrison', 56), ('Ken', 'Wolseley', 23), ('Emily', 'Robinson', 77)]

  def get_first_item(lst):
    return lst[0]

  def get_second_item(lst):
    return lst[1]

  def get_third_item(lst):
    return lst[2]

  by_first_name = sorted(people, key=get_first_item)
  by_last_name = sorted(people, key=get_second_item)
  by_age = sorted(people, key=get_third_item)
  ```
</details>

### 4. Write a function called `dict_intersect` that takes two dictionaries, `d1` and `d2`, as arguments and returns a set that contains only the keys found in both of the original dictionaries.

HINT: Let's break this down into steps. We need to:
*   Get the keys in `d1`
*   Get the keys in  `d2`
*   Convert them both to sets
*   Find their intersection

HINT: Some useful functions and methods are `keys()`, `set()`, and `intersection()`.

In [46]:
# Your code goes here
def dict_intersect(d1, d2):
    keys_d1 = d1.keys()
    keys_d2 = d2.keys()
    keys_d1_set = set(keys_d1)
    keys_d2_set = set(keys_d2)
    same_set = keys_d1_set.intersection(keys_d2_set)
    return same_set

# or the concise method
def dict_intersect(d1, d2):
    d1_keys = set(d1.keys())
    d2_keys = set(d2.keys())
    return d1_keys.intersection(d2_keys)

In [47]:
dict1 = {"Canada":"Ottawa",
         "USA": "Washington", 
         "Mexico": "Mexico City",
         "Germany": "Berling"}

dict2 = {"Canada":"41 million",
         "USA":"330 million",
         "Russia": "180 million",
         "Australia": "28 million"}

dict_intersect(dict1, dict2)

{'Canada', 'USA'}

<details>
  <summary>Answer</summary>

  ```python
  def dict_intersect(d1, d2):
    '''Return the set of keys found in both d1 and d2.
    >>> dict_intersect({'a': 'A', 'b': 'B', 'c': 'C'}, {'a': 'alpha', 'b': 'beta'})
    {'a', 'b'}
    >>> dict_intersect({'a': 1, 'b': 2}, {'c': 3, 'd': 2})
    set()
    '''
    d1_keys = set(d1.keys())
    d2_keys = set(d2.keys())
    return d1_keys.intersection(d2_keys)
  ```
</details>

### 5. Write a loop that iterates over the two lists below simultaneously. For each pair of values, print the first number divided by the second. When the program encounters a zero divisor, it should skip the pair without printing anything.  

HINT: We can exit a loop early with `break`.

HINT 2: Remember that we can bundle two lists pairwise with `zip()`.

In [55]:
# Your code goes here
list1 = [10, 20, 30, 40]
list2 = [1, 0, 2, 3]

for i, j in zip(list1, list2):
    if i == 0 or j == 0:
        continue 
    else:
        print(i / j)

# make the continue chekpoint first
# it allows to validate the the data if it is a 0 divisor or not

10.0
15.0
13.333333333333334

<details>
  <summary>Answer</summary>

  ```python
  dividends = [100, 37.5, -12]
  divisors = [8, 0, -3]

  for x, y in zip(dividends, divisors):
    if y == 0:
      continue
    else:
      print(x/y)
  ```
</details>